name: Build Android and iOS

on: [push]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          yarn
      - name: Run tests
        run: |
          yarn test --coverage
          bash <(curl -s https://codecov.io/bash)
