name: Build Android and iOS

on: [push]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Write File
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ env.home}}/env.json
          contents: |
            echo "Hello World!"
          write-mode: overwrite
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Install yarn dependencies
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          yarn
      - name: Run lint
        run: |
          yarn lint
      - name: Run tests
        run: |
          yarn test
          bash <(curl -s https://codecov.io/bash)
