name: Build Android and iOS in Main

on: [push]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn
      - name: Run tests
        run: |
          yarn test
        run: |
          bash <(curl -s https://codecov.io/bash)
