name: Build Android and iOS

on: [push]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Install yarn dependencies
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          yarn
      - name: Run lint
        run: |
          yarn lint
      - name: Create env file
        run: |
          touch env.js
          echo "
          export default {
            product_name: '${{ secrets.PRODUCT_NAME }}',
          };
          " >> env.js
          cat env.js
      - name: Run tests
        run: |
          yarn test
          bash <(curl -s https://codecov.io/bash)
